add footer and necessary svg in sprite
Burla4enko/ice-cream-team-project pull request #13
Opened 2022-07-23 19:10 UTC by Roman-Vanchytskyi

2022-07-23 20:41 UTC, Burla4enko requested changes

2022-07-23 20:41 UTC, Burla4enko commented on src/sass/components/_footer.scss
> +
Футеру нужен фон, иначе: 
![image](https://user-images.githubusercontent.com/45729176/180620850-9871d3c0-b472-473d-b990-56eb642f2eb0.png)

2022-07-23 20:41 UTC, Burla4enko commented on src/sass/components/_footer.scss
> +  display: flex;
убрать flex. Мобилка без флекс, можно блоками сделать

2022-07-23 20:41 UTC, Burla4enko commented on src/sass/components/_footer.scss
> +  flex-direction: column;
убрать

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +    <span class="footer__reserved-text1"> &copy; 2022 - IceCream.&nbsp;</span>
Зачем плодить классы? Сделай один для двух span'ов

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +  <div class="footer__reserved container">
измени название класса, т.к.  reserved = "зарезервировано", не понятно что в классе. Назови
.footer__copyright

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +    <span class="footer__reserved-text1"> &copy; 2022 - IceCream.&nbsp;</span>
.footer__copyright-text

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +    <span class="footer__reserved-text2">&nbsp;All Rights Reserved.</span>
.footer__copyright-text

2022-07-23 20:41 UTC, Burla4enko commented on src/sass/components/_footer.scss
> +}
.footer__copyright-text 
сделай их на мобилке display: block; - они станут в столбик, с таблетки сделай display: inline;

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +    <div class="footer__flex">
зачем этот div? у тебя section выступает в роли обёртки. Удали. 
У тебя в section только этот div и всё....
стилей у него нет...

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +      <div class="footer__tabl-item1">
назови класс .footer__slogan 
.footer__tabl-item1 - непонятно что делает этот класс

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +        <p class="footer__text-small">homemade ice cream made</p>
.footer__slogan-suptitle

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +        <p class="footer__text-large">with passion</p>
.footer__slogan-title
название классов должно указывать, что это.
Перечитай конспект про БЭМ

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +      <div class="footer__tabl-item2">
переименуй в .footer__contacts

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +        <ul class="footer__soc-list list">
переименуй в .footer__socials
Удали класс list - он ничего не делает

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +            <a
добавь в `<a>` rel="nofollow noreferrer noopener"

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +            <a
добавь в `<a>` rel="nofollow noreferrer noopener"

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +            <a
добавь в `<a>` rel="nofollow noreferrer noopener"

2022-07-23 20:41 UTC, Burla4enko commented on src/sass/components/_footer.scss
> +  gap: 28.24px;
округли до 28рх

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +        <div class="footer__title">
класс .footer__title поменяй на .footer__phone

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +          <span class="footer__title-prenumber"
.footer__phone-text

prenumber - означает предварительный номер

2022-07-23 20:41 UTC, Burla4enko commented on src/partials/footer.html
> +          <a href="tel:+610383766284" class="footer__title-number"
.footer__phone-number

2022-07-23 21:00 UTC, Roman-Vanchytskyi commented on src/sass/components/_footer.scss
> +
ok

2022-07-23 21:06 UTC, Roman-Vanchytskyi commented on src/sass/components/_footer.scss
> +  display: flex;
ok

2022-07-23 21:08 UTC, Roman-Vanchytskyi commented on src/sass/components/_footer.scss
> +  flex-direction: column;
ok

2022-07-23 21:12 UTC, Roman-Vanchytskyi commented on src/partials/footer.html
> +    <span class="footer__reserved-text1"> &copy; 2022 - IceCream.&nbsp;</span>
ok

2022-07-23 21:12 UTC, Roman-Vanchytskyi commented on src/partials/footer.html
> +  <div class="footer__reserved container">
ok

2022-07-23 21:15 UTC, Roman-Vanchytskyi commented on src/partials/footer.html
> +            <a
ok

2022-07-23 21:15 UTC, Roman-Vanchytskyi commented on src/sass/components/_footer.scss
> +  gap: 28.24px;
ok

2022-07-23 21:18 UTC, Roman-Vanchytskyi commented on src/partials/footer.html
> +          <span class="footer__title-prenumber"
ok

2022-07-23 21:18 UTC, Roman-Vanchytskyi commented on src/partials/footer.html
> +        <div class="footer__title">
ok

2022-07-23 21:19 UTC, Roman-Vanchytskyi commented on src/partials/footer.html
> +          <a href="tel:+610383766284" class="footer__title-number"
ok

2022-07-24 22:19 UTC, Burla4enko approved these changes

2022-07-24 22:20 UTC, merged