Advantages 1.0
Burla4enko/ice-cream-team-project pull request #14
Opened 2022-07-23 21:32 UTC by MrKobernyk

2022-07-23 22:48 UTC, Burla4enko requested changes

2022-07-23 22:48 UTC, Burla4enko commented on src/sass/components/_advantages.scss
> +    padding-bottom: 60px;
используй переменную
 --section-padding: 60px;

2022-07-23 22:48 UTC, Burla4enko commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__milk-svg">721</p>
advantages__milk-svg - зачем плодить классы? Удали
они у тебя одинаковые, только ссылки на файлы разные

2022-07-23 22:48 UTC, Burla4enko commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__apples-svg">16KG</p>
advantages__apples-svg - зачем плодить классы? Удали
они у тебя одинаковые, только ссылки на файлы разные

2022-07-23 22:48 UTC, Burla4enko commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__heart-svg">84</p>
advantages__heart-svg - зачем плодить классы? Удали
они у тебя одинаковые, только ссылки на файлы разные

2022-07-23 22:48 UTC, Burla4enko commented on src/sass/components/_advantages.scss
> +    &__milk-svg::before {
сделай общий стиль к `.advantages__ammount::before {
content: '';
        display: block;
        width: 33px;
        height: 50px;      
        background-repeat: no-repeat;
        margin-bottom: 16px;
}

.advantages__ammount:nth-child(1)::before {
background-image: url("../images/advantages-svg/milk.svg");
}`

И так далее

2022-07-23 22:48 UTC, Burla4enko commented on src/sass/components/_advantages.scss
> +        width: 33px;
100%, вдруг картинку шире поставят

2022-07-23 22:48 UTC, Burla4enko commented on src/sass/components/_advantages.scss
> +
background-position: left center;
если поставят маленькую картинку, чтобы она не сбилась в расположении

2022-07-23 22:48 UTC, Burla4enko commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__apples-svg">16KG</p>
amount - c 1 m

2022-07-23 22:48 UTC, Burla4enko commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__milk-svg">721</p>
amount - c 1 m

2022-07-23 22:48 UTC, Burla4enko commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__heart-svg">84</p>
amount - c 1 m

2022-07-23 22:48 UTC, Burla4enko commented on src/sass/components/_advantages.scss
> +        display: flex;
убери флекс на мобилке, просто блочные элементы

2022-07-23 22:48 UTC, Burla4enko commented on src/sass/components/_advantages.scss
> +
.advantages__item - как уберёшь у родителя флекс, сюда margin-bottom поставишь

2022-07-24 08:43 UTC, MrKobernyk commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__milk-svg">721</p>
переделал через модификаторы, не сильно лучше, но по тз заставили сделать через псевдоэлементы, я бы вообще так не делал - сразу бы svg поставил в html. У них ещё размер разный(

2022-07-24 08:43 UTC, MrKobernyk commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__apples-svg">16KG</p>
+

2022-07-24 08:43 UTC, MrKobernyk commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__heart-svg">84</p>
+

2022-07-24 08:44 UTC, MrKobernyk commented on src/sass/components/_advantages.scss
> +    &__milk-svg::before {
аа, ок, спасибо

2022-07-24 09:33 UTC, MrKobernyk commented on src/sass/components/_advantages.scss
> +    &__milk-svg::before {
.advantages__ammount:nth-child(1)::before - так не работает, каждый before в своей li считает себя first child((
сделал так - &__item:nth-child(1) &__amount::before

2022-07-24 09:34 UTC, MrKobernyk commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__apples-svg">16KG</p>
done

2022-07-24 09:34 UTC, MrKobernyk commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__milk-svg">721</p>
done

2022-07-24 09:34 UTC, MrKobernyk commented on src/partials/advantages.html
> +        <p class="advantages__ammount advantages__heart-svg">84</p>
done

2022-07-24 09:35 UTC, MrKobernyk commented on src/sass/components/_advantages.scss
> +        display: flex;
ок, но тогда марджины появятся в мобилке...потом их обнулять..

2022-07-24 09:35 UTC, MrKobernyk commented on src/sass/components/_advantages.scss
> +
ок

2022-07-24 18:10 UTC, Burla4enko approved these changes

2022-07-24 18:12 UTC, Burla4enko approved these changes

2022-07-24 18:13 UTC, merged