feature/products
Burla4enko/ice-cream-team-project pull request #3
Opened 2022-07-22 15:53 UTC by Roman-Huminilovych

I add section Products in mobile, tablet and desktop versions.

2022-07-23 13:47 UTC, Burla4enko requested changes

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
> +        <p class="products__item-title">ice cream</p>
Итак, нужно поменять немного структуру карточки, обернуть дополнительно в div и к нему применить стили фона. Поиграйся с ними, чтобы соответствовало макету.
![image](https://user-images.githubusercontent.com/45729176/180606460-52afe946-7e1e-409d-9121-25bb097d9631.png)
![image](https://user-images.githubusercontent.com/45729176/180606497-7037c44f-79bc-408f-a8f9-4f1720be62ad.png)

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
>      <span class="products__lable">100% natural</span>
поменяй тег на `<p>` т.к. `<span>` используют для выделения части текста, уже состоящем в текстовом блоке

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
>      <span class="products__lable">100% natural</span>
измени на класс .section__suptitle - этот класс будет у всех, его пропишем позже.

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
>      <h2 class="products__title">products</h2>
измени на класс .section__title - этот класс будет у всех, его пропишем позже.

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
> +      <li class="products__item products__item-pink">
products__item--pink - модификатор через два дефиса

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
> +      <li class="products__item products__item-yellow">
products__item--yellow - модификатор через два дефиса

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
> +        <p class="products__item-title">ice coffee</p>
поменять немного структуру карточки, обернуть дополнительно в div и к нему применить стили фона

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
> +        <p class="products__item-title">milkshakes</p>
поменять немного структуру карточки, обернуть дополнительно в div и к нему применить стили фона

2022-07-23 13:47 UTC, Burla4enko commented on src/partials/products.html
> +      <li class="products__item products__item-green">
products__item--green - модификатор через два дефиса

2022-07-23 13:47 UTC, Burla4enko commented on src/sass/components/_products.scss
>    text-transform: uppercase;
избавиться от ОГРОМНЫХ margin-bottom'ов в этом классе, на всех разрешениях от мобильного до десктопа
изменение конструкции поможет, на скринах выше видны изменения

2022-07-23 13:47 UTC, Burla4enko commented on src/sass/components/_products.scss
>    margin-bottom: 130px;
его нет в макете, убрать

2022-07-23 13:47 UTC, Burla4enko commented on src/sass/components/_products.scss
>    padding-bottom: 40px;
используй короткую запись padding: 160px 40px 40px; - после изменения структуры будут другие верх-низ отступы

2022-07-24 21:59 UTC, Apdayk commented on src/sass/components/_products.scss
Надо бы добавить **margin-bottom: 5px;** хотя бы на тот случай если картинки не загрузятся, что бы карточки не прилипали в 0 друг к другу.

2022-07-25 00:45 UTC, Burla4enko approved these changes

2022-07-25 00:45 UTC, merged