Feature/mobile menu
Burla4enko/ice-cream-team-project pull request #9
Opened 2022-07-23 11:18 UTC by SvitlanaIvanenko

2022-07-23 18:46 UTC, Burla4enko requested changes

2022-07-23 18:46 UTC, Burla4enko commented on src/sass/components/_header.scss
> +    padding-bottom: 25px;
padding поставь 8 будет лучше ;)

2022-07-23 18:46 UTC, Burla4enko commented on src/partials/header.html
> +        <div class="menu is-hidden">
вместо div - симантический тег nav

2022-07-23 18:46 UTC, Burla4enko commented on src/partials/header.html
> +                <button type="button" class="menu__close-btn">
Зfчем ещё один button? Сделай как в нашем ДЗ 8, одну кнопку с двумя картинками SVG

2022-07-23 18:46 UTC, Burla4enko commented on src/partials/header.html
> +            <button type="button" class="header__open-btn">
название классов - БЛОК__ЭЛЕМЕНТ, у нас нет элемента open, у нас есть элемент btn с добавкой open
.header__btn-open

2022-07-23 18:46 UTC, Burla4enko commented on src/partials/header.html
> +        <div class="menu is-hidden">
Почему меню не внутри .header? Это не часть хедера, а его сосед?
Посмотри, чтобы это потом не вызвало проблем с tablet и desctop.
![image](https://user-images.githubusercontent.com/45729176/180617995-f830acd6-b0a8-489a-8209-c4b757e48c02.png)

2022-07-23 18:46 UTC, Burla4enko commented on src/partials/header.html
> +                <button type="button" class="buy__btn">
название класса другое. У нас нет блока buy к которому относится элемент btn
.menu__btn

2022-07-23 18:46 UTC, Burla4enko commented on src/sass/components/_mobile_menu.scss
> +    width: 209px;
убрать ширину и высоту фиксированные, сделать min-width и min-height 
достичь размер padding'ом
![image](https://user-images.githubusercontent.com/45729176/180618616-f774a140-ff65-4990-8348-4a27a894f45e.png)
![image](https://user-images.githubusercontent.com/45729176/180618664-7ea925b4-6751-4dcc-997c-d1e8cf41d389.png)

2022-07-23 18:46 UTC, Burla4enko commented on src/sass/components/_mobile_menu.scss
> +    font-family: var(--font-main);
расширить паддингами, чтобы она не была такой маленькой, чтобы не тыкать прицельно пальцем на телефоне
Размер как в макете:
![image](https://user-images.githubusercontent.com/45729176/180618791-385f3013-5ac7-4390-963a-ef9470b9858e.png)

![image](https://user-images.githubusercontent.com/45729176/180618743-8ce15fe9-1237-4162-9969-d668fb3abaa0.png)

2022-07-23 18:46 UTC, Burla4enko commented on src/sass/components/_mobile_menu.scss
> +   .nav__link {
нет border у пунктов меню, как в макете

2022-07-23 19:52 UTC, SvitlanaIvanenko commented on src/sass/components/_mobile_menu.scss
> +   .nav__link {
+

2022-07-23 19:52 UTC, SvitlanaIvanenko commented on src/sass/components/_mobile_menu.scss
> +    font-family: var(--font-main);
done

2022-07-23 19:58 UTC, SvitlanaIvanenko commented on src/sass/components/_mobile_menu.scss
> +    width: 209px;
done

2022-07-23 20:01 UTC, SvitlanaIvanenko commented on src/partials/header.html
> +                <button type="button" class="buy__btn">
done

2022-07-23 20:04 UTC, SvitlanaIvanenko commented on src/partials/header.html
> +            <button type="button" class="header__open-btn">
done

2022-07-23 20:06 UTC, SvitlanaIvanenko commented on src/partials/header.html
> +                <button type="button" class="menu__close-btn">
тому що це різні кнопки (і в дз також були)

2022-07-23 20:08 UTC, SvitlanaIvanenko commented on src/sass/components/_header.scss
> +    padding-bottom: 25px;
наче ж стоїть) верхній

2022-07-23 20:16 UTC, SvitlanaIvanenko commented on src/partials/header.html
> +        <div class="menu is-hidden">
done
частина хедера

2022-07-24 22:51 UTC, Burla4enko approved these changes

2022-07-24 22:57 UTC, merged